### ISSUE TITLE
problem with \textbf redefinition

### ISSUE THREAD

**Issue by giocic2** [trincadev/cv-latex-twentyoneseconds#4]
I would like to **bold** some words, but you have redefined the behaviour of the \textbf command

**Comment by trincadev** [comment]
Hi @giocic2, sorry about the delay. I'll try to look about this as soon as possible.

**Comment by giocic2** [comment]
no problem, i made a pull request to solve this problem

**Comment by trincadev** [comment]
Thank you, I approved your PR 👍
